   name: build

   on:
     push:
       branches: [ master ]
     pull_request:
       branches: [ master ]

   jobs:
    build:
      runs-on: ${{ matrix.config.os }}
      strategy:
        matrix:
          config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: build application
        run: make
