  name: release

  on:
    release:
      types: [created]

  jobs:
     build:
      runs-on: ${{ matrix.config.os }}
      strategy:
        matrix:
          config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@master
      - name: build application
        shell: bash
        run: make release
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: hideur_maikeur-${{ matrix.config.os }}-${{ github.ref_name }}.7z
          # The path to the file you want to upload.
          asset_path: ./hideur.7z
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/octet-stream
